const express = require("express")
const Router = express.Router()

const hotelRoutes = require("./hotel")
const stockRoutes = require("./stock")
const expenseRoutes = require("./expense")
const cashSessionRoutes = require("./cashSession")
const recipesRoutes = require("./recipes")
const semiFinishedRoutes = require("./semiFinishedItems")
const webSiteRoutes = require("./website")
const reportRoutes = require("./report")
const promoCodeRoutes = require("./promoCode")
const zomato = require("./zomato")
const customer = require("./customer")
const merchant = require("./merchant")
const merchantReport = require("./merchantReport")
const kitchen = require("./kitchen")
const taxType = require("./tax")
const subscription = require("./subscription")
const payment = require("./payment")
const superAdmin = require("./superAdmin")
const mobileRoutes = require("./mobile")
const ticketRoutes = require("./ticket")
const franchiseRoute = require("./franchise")
const crmRoutes = require("./crm")
const syncRoutes = require("./sync")
const { verifyWebhook: verifyMetaWebhook, receiveLeadEvent: receiveMetaLeadEvent } = require("../controller/crm/metaWebhookController")

Router.use("/", hotelRoutes)
// Sync engine v2 - a restaurant's local exe only (device token, not a
// person's session). See routes/sync.js.
Router.use("/sync", syncRoutes)
Router.use("/stock", stockRoutes)
Router.use("/mobile", mobileRoutes)
Router.use("/promocodes", promoCodeRoutes)
Router.use("/subscription", subscription)
Router.use("/expense", expenseRoutes)
Router.use("/cashSession", cashSessionRoutes)
Router.use("/recipes", recipesRoutes)
Router.use("/semiFinished", semiFinishedRoutes)
Router.use("/website", webSiteRoutes)
Router.use("/report", reportRoutes)
Router.use("/zomato", zomato)
Router.use("/customer", customer)
Router.use("/merchant", merchant)
Router.use("/merchant/report", merchantReport)
Router.use("/kitchen", kitchen)
Router.use("/taxType", taxType)
Router.use("/payment", payment)
Router.use("/superAdmin", superAdmin)
Router.use("/ticket", ticketRoutes)
Router.use("/franchise", franchiseRoute)
// Public — Meta calls these without auth, so they must be registered ahead of the
// auth-gated /crm router (which applies superAdminAuth + loadCrmProfile to everything).
Router.get("/crm/meta/webhook", verifyMetaWebhook)
Router.post("/crm/meta/webhook", receiveMetaLeadEvent)

Router.use("/crm", crmRoutes)

module.exports = Router